### ISSUE TITLE
Combine date expression lists instead of using list comprehension in get archival object data submodule

### ISSUE THREAD

**Issue by p-galligan** [RockefellerArchiveCenter/iiif-image-scripts#40]
## Is your feature request related to a problem? Please describe.
Line 64 (`expressions = [date.get('expression') for date in ao_date]`) will not work as expected. 

## Describe the solution you'd like
Directly join lists.

**Comment by helrond** [comment]
I would propose that you do any date manipulation outside of the `get_ao` submodule, and instead do that where you use the expression in the manifest creation. That helps to keep what `get_ao` is doing very concise - it's just getting an object back from ArchivesSpace that you know will have a title and a date.
