### ISSUE TITLE
Source filepath cannot contain spaces

### ISSUE THREAD

**Issue by bonniegee** [RockefellerArchiveCenter/iiif-image-scripts#67]
## Describe the bug
When providing a directory path with spaces as the source directory, the script fails when running the `opj_compress` command. This happens when providing the directory path  in double quotes or escaping the spaces using a backslash.

## To reproduce
Run the script over a directory that contains spaces in its path.

## Expected behavior
Paths for source directories can include spaces.

## Error message or screenshots
```command '['/usr/local/bin/opj_compress -i /mnt/xdrive/Projects/Reference Digitization/Uploaded_IIIF/94a9865034f8430bb4efe857825c4012/master/94a9865034f8430bb4efe857825c4012_002.tif -o tmp/images/VUDsYHErtMTUPkb7Lb8VWQ_002.jp2 -n 6 -r 1.5 -c [256,256],[256,256],[128,128] -b 64,64 -p RPCL -SOP']' returned with error (code 1): b'[ERROR] Unknown input file format: /mnt/xdrive/Projects/Reference \n        Known file formats are *.pnm, *.pgm, *.ppm, *.pgx, *png, *.bmp, *.tif, *.raw or *.tga\n'```

## Impact on your work
Current workaround is to move the source directory to a path that does not contain spaces, so this is not a blocker.

## Additional context
It appears that this issue is happening when using `subprocess` in the `create_jp2` method. The `os.path.isdir` check in `pipeline.py` is passing before the subprocess command that's throwing the error.

**Comment by helrond** [comment]
Looks like the solution is to pass the command as a list, and wrap the path in quotes: https://stackoverflow.com/questions/25655173/does-pythons-subprocess-popen-accept-spaces-in-paths
