### ISSUE TITLE
Handle more variations in filename numbers

### ISSUE THREAD

**Issue by bonniegee** [RockefellerArchiveCenter/iiif-image-scripts#80]
## Is your feature request related to a problem? Please describe.
Filenames that are numbered sequentially, but do not have an `_` in the filename, cause the pipeline to fail. Given this and the variation described in #78, getting the page number in `derivatives.py` should handle more complexity.

## Describe the solution you'd like
[This line](https://github.com/RockefellerArchiveCenter/iiif-pipeline/blob/base/iiif_pipeline/derivatives.py#L59) should be broken out into a `get_page_number` helper method. This method should be able to handle the following:

- Filenames that end in `_001`
- Filenames that end in `_001_me` or `_001_se`
- Filenames like `000000001`

**Comment by helrond** [comment]
fixed in 5a146ad0603355fd19d8927a6c0c8fc95b4f2d14
